spring.application.name=demo
spring.liquibase.change-log=/db/changelog/master.xml

# Narayana + agroal
spring.datasource.agroal.min-size=4
spring.datasource.agroal.max-size=30
spring.datasource.agroal.max-lifetime=2700
spring.datasource.agroal.acquisition-timeout=60
narayana.messaginghub.enabled=true
narayana.messaginghub.max-connections=30
narayana.log-dir=target/xa-transactions-logs
narayana.default-timeout=3600
narayana.transactional-driver.pool.enabled=true

# JPA
spring.jpa.open-in-view=false

# see https://vladmihalcea.com/hibernate-aggressive-connection-release/
#spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_HOLD
#spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
#spring.jpa.properties.hibernate.connection.handling_mode=IMMEDIATE_ACQUISITION_AND_HOLD

# Log
logging.level.root=warn
